# Site settings
title: Engage807
email: webmaster@thesummitfw.com
description: > # this means to ignore newlines until "baseurl:"
 The Engage807 Culinary Incubator at The Summit in Fort Wayne, Indiana, provides a 2200 square foot commercial kitchen for culinary entrepreneurs.
baseurl: "/engage807" # the subpath of your site, e.g. /blog/
url: "http://engage807.com" # the base hostname & protocol for your site
logo: "/images/engage807.png"
encoding: utf-8
highlighter: rouge
# Build settings
markdown: kramdown

sass:
    style: :compressed